"""subscription id

Revision ID: a8fe0f9de229
Revises: 89e56ed4223d
Create Date: 2019-10-04 20:51:17.343538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fe0f9de229'
down_revision = '89e56ed4223d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscription_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription_id')
    # ### end Alembic commands ###
